-- MySQL Script generated by MySQL Workbench
-- Wed Mar 31 20:29:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agricolas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agricolas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agricolas` DEFAULT CHARACTER SET utf8 ;
USE `agricolas` ;

-- -----------------------------------------------------
-- Table `agricolas`.`Proprietarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agricolas`.`Proprietarios` (
  `idProprietarios` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Morada` VARCHAR(45) NOT NULL,
  `NF` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProprietarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agricolas`.`PropriedadesAgricolas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agricolas`.`PropriedadesAgricolas` (
  `idPropriedadesAgricolas` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Distrito` VARCHAR(45) NOT NULL,
  `Concelho` VARCHAR(45) NOT NULL,
  `Freguesia` VARCHAR(45) NOT NULL,
  `artigoMatricial` INT NOT NULL,
  `Culturas` VARCHAR(45) NOT NULL,
  `Proprietarios_idProprietarios` INT NOT NULL,
  PRIMARY KEY (`idPropriedadesAgricolas`, `Proprietarios_idProprietarios`),
  INDEX `fk_PropriedadesAgricolas_Proprietarios_idx` (`Proprietarios_idProprietarios` ASC) VISIBLE,
  CONSTRAINT `fk_PropriedadesAgricolas_Proprietarios`
    FOREIGN KEY (`Proprietarios_idProprietarios`)
    REFERENCES `agricolas`.`Proprietarios` (`idProprietarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
